HEADLESS_TEST1 = "https://arh.antoinevastel.com/bots/areyouheadless"
HEADLESS_TEST2 = "https://intoli.com/blog/making-chrome-headless-undetectable/chrome-headless-test.html"
HEADLESS_TEST3 = "https://bot.sannysoft.com/"
WEBRTC = "https://privacycheck.sec.lrz.de/active/fp_wrtc/fp_webrtc.html#fpWebRTC"
IP_CHECK = "https://ipinfo.io/ip"
WEBCAM_CHECK = "https://webcamtests.com/"
FINGERPRINT_STUNDZIALT = "http://www.xn--stundia-hxb.lt/fingerprint"
